services:
  tts:
    build:
      context: .
      dockerfile: Dockerfile
    image: heartale
    container_name: heartale
    ports:
      - 18081:8080
    volumes:
      - .:/app
      - ./logs:/logs
    restart: on-failure
    environment:
      - TZ=Asia/Shanghai
