version: 1.0.0
proxy: None
max_time: 10
max_chapter: 20
server:
  key: legado
  legado:
    host: 192.168.1.176
    port: 1122
  text:
    path: /tmp/temp.txt
    encoding: utf-8
  reader:
    host: reader
    port: 8080
tts:
  key: sherpa
  edge:
    host: 127.0.0.1
    port: 18081
    voice: zh-CN-XiaoxiaoNeural
    rate: 30
  sherpa:
    model_config: ./models/config.yaml
    sid: 0
    speed: 1.4
