name: 自动打包

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]


permissions:
  contents: write  # 确保具有写权限

env:
  TAG_NAME: "beta"
  SOFTWARE_NAME: "heartale"


jobs:
  build-lfy:
    runs-on: ubuntu-24.04
    steps:
    - uses: actions/checkout@v4
    - name: build
      run: |
        python -m pip install --upgrade pip
        pip install pylint build
        python -m build
        pip install ./dist/*.whl

    - name: Release
      uses: softprops/action-gh-release@v2
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ env.TAG_NAME }}
        prerelease: true
        draft: false
        files: |
          dist/*.whl
